name="hanan"
print(name)
n="hello"
print(n+name)
print(name[4])
print(name[:3])
print(name[1:4])
print(name[0:])
print(name[-1])
print(name[1:4:2])
print(len(name))
name=name.count("a")
print(name)